# serverless.yml

org: seanaye
app: my-first-app

service: graphql-test

provider:
  name: aws
  runtime: python3.8

functions:
  graphql:
    handler: asgi/main.handler
    events:
      - httpApi: '*'


plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
